function matlab_ab_policy_smoke()
% matlab_ab_policy_smoke: Fast smoke test for A/B benchmark outputs.

    repo_root = fileparts(mfilename('fullpath'));
    addpath(fullfile(repo_root, 'src', 'matlab'));

    config = buildABConfig( ...
        'run_id', 'smoke_run', ...
        'paired_seed_count', 2, ...
        'scenario_names', {'nominal_handoff', 'strong_pause_near_zone'}, ...
        'backend', 'heuristic_stub');
    summary = matlab_run_ab_policy_benchmark( ...
        'run_id', config.run_id, ...
        'paired_seed_count', config.paired_seed_count, ...
        'scenario_names', config.scenario_names, ...
        'backend', config.backend);

    run_dir = fullfile(config.output_base_dir, config.run_id);
    required_files = {
        'run_config.json', ...
        'episode_metrics.csv', ...
        'pairwise_deltas.csv', ...
        'scenario_policy_summary.csv', ...
        'summary.mat', ...
        'summary.txt', ...
        'completion_time_boxplot.png', ...
        'safety_events_bar.png', ...
        'wait_time_tradeoff_bar.png', ...
        'response_latency_bar.png'
    };

    for idx = 1:numel(required_files)
        assert(exist(fullfile(run_dir, required_files{idx}), 'file') == 2, 'Missing artifact: %s', required_files{idx});
    end
    assert(numel(summary.episode_metrics) == 8, 'Expected 8 episodes in smoke run.');
    fprintf('MATLAB A/B smoke test passed.\n');
end
