function config = buildABConfig(varargin)
% buildABConfig: Return deterministic configuration for MATLAB A/B benchmark.
%
% Supports name/value overrides on top-level fields for smoke and expected checks.

    repo_root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
    timestamp = datestr(now, 'yyyymmdd_HHMMSS');

    config = struct();
    config.repo_root = repo_root;
    config.output_base_dir = fullfile(repo_root, 'reports', 'matlab_validation', 'ab_milestone1');
    config.run_id = ['run_', timestamp];
    config.backend = 'heuristic_stub';
    config.enable_plots = true;
    config.write_outputs = true;

    config.dt_sec = 0.1;
    config.frame_rate_hz = 10;
    config.max_frames = 300;
    config.window_size_frames = 20;
    config.inference_stride_frames = 5;
    config.warmup_frames = 20;

    config.paired_seed_count = 20;
    config.scenario_names = {
        'nominal_handoff', ...
        'mild_pause_approach', ...
        'strong_pause_near_zone', ...
        'correction_rework_midtask', ...
        'robot_overlap_pressure' ...
    };
    config.policy_names = {'A', 'B'};
    config.seed_start = 101;

    config.workspace = struct( ...
        'bounds_xy', [0.0, 1.0; 0.0, 1.0], ...
        'shared_zone_center_xy', [0.55, 0.50], ...
        'shared_zone_radius_m', 0.12, ...
        'hard_safety_radius_m', 0.10, ...
        'emergency_release_radius_m', 0.14, ...
        'human_start_xy', [0.10, 0.50], ...
        'robot_start_xy', [0.90, 0.50], ...
        'human_waypoints_xy', [ ...
            0.10, 0.50; ...
            0.40, 0.50; ...
            0.55, 0.50; ...
            0.25, 0.70 ...
        ], ...
        'robot_waypoints_xy', [ ...
            0.90, 0.50; ...
            0.70, 0.55; ...
            0.55, 0.50; ...
            0.82, 0.70 ...
        ]);

    config.human = struct( ...
        'crowding_mild_threshold_m', 0.22, ...
        'crowding_strong_threshold_m', 0.18, ...
        'crowding_mild_frames', 3, ...
        'crowding_strong_frames', 15, ...
        'stable_release_frames', 10, ...
        'pause_every_n_frames', 4, ...
        'mild_speed_scale', 0.45, ...
        'strong_speed_scale', 0.10, ...
        'strong_micro_step_scale', 0.15, ...
        'waypoint_tolerance_m', 0.035);

    config.policy_a = struct( ...
        'default_speed_scale', 1.0);

    config.policy_b = struct( ...
        'hold_future_hesitation_threshold', 0.70, ...
        'hold_future_correction_threshold', 0.50, ...
        'slow_future_hesitation_threshold', 0.40, ...
        'slow_separation_threshold_m', 0.20, ...
        'slow_speed_scale', 0.40, ...
        'low_risk_future_hesitation_threshold', 0.25, ...
        'low_risk_future_correction_threshold', 0.20, ...
        'release_required_ticks', 8);

    config.heuristic = struct( ...
        'pause_ratio_strong', 0.55, ...
        'pause_ratio_mild', 0.25, ...
        'mean_speed_strong', 0.03, ...
        'mean_speed_mild', 0.08, ...
        'distance_mild', 0.18, ...
        'reversal_mild_count', 2, ...
        'rework_progress_delta_threshold', 0.02);

    config.metrics = struct( ...
        'timeline_seed', 1, ...
        'timeline_scenario', 'strong_pause_near_zone');

    config.python = struct( ...
        'model_root_dir', repo_root, ...
        'python_cmd', 'python3');

    config = applyNameValueOverrides(config, varargin{:});
end

function config = applyNameValueOverrides(config, varargin)
    if mod(numel(varargin), 2) ~= 0
        error('buildABConfig requires name/value overrides.');
    end

    for idx = 1:2:numel(varargin)
        name = varargin{idx};
        value = varargin{idx + 1};
        if ~ischar(name) && ~isstring(name)
            error('Override keys must be char or string.');
        end
        config.(char(name)) = value;
    end
end
