function scenarios = buildABScenarioLibrary()
% buildABScenarioLibrary: Return initial scenario family definitions.

    scenarios = struct([]);

    scenarios(1) = struct( ...
        'name', 'nominal_handoff', ...
        'human_speed_range', [0.085, 0.100], ...
        'robot_speed_range', [0.080, 0.095], ...
        'hesitation_progress_range', [0.00, 0.00], ...
        'hesitation_duration_range', [0, 0], ...
        'escalation', false, ...
        'rework_progress_range', [0.00, 0.00], ...
        'jitter_scale', 0.002, ...
        'crowding_sensitivity_threshold_m', 0.22, ...
        'early_robot_release_frames', 18);

    scenarios(2) = struct( ...
        'name', 'mild_pause_approach', ...
        'human_speed_range', [0.080, 0.095], ...
        'robot_speed_range', [0.080, 0.095], ...
        'hesitation_progress_range', [0.35, 0.55], ...
        'hesitation_duration_range', [18, 28], ...
        'escalation', false, ...
        'rework_progress_range', [0.00, 0.00], ...
        'jitter_scale', 0.003, ...
        'crowding_sensitivity_threshold_m', 0.215, ...
        'early_robot_release_frames', 18);

    scenarios(3) = struct( ...
        'name', 'strong_pause_near_zone', ...
        'human_speed_range', [0.075, 0.090], ...
        'robot_speed_range', [0.085, 0.100], ...
        'hesitation_progress_range', [0.50, 0.70], ...
        'hesitation_duration_range', [28, 42], ...
        'escalation', true, ...
        'rework_progress_range', [0.00, 0.00], ...
        'jitter_scale', 0.0035, ...
        'crowding_sensitivity_threshold_m', 0.205, ...
        'early_robot_release_frames', 20);

    scenarios(4) = struct( ...
        'name', 'correction_rework_midtask', ...
        'human_speed_range', [0.078, 0.092], ...
        'robot_speed_range', [0.082, 0.098], ...
        'hesitation_progress_range', [0.20, 0.35], ...
        'hesitation_duration_range', [10, 20], ...
        'escalation', false, ...
        'rework_progress_range', [0.60, 0.75], ...
        'jitter_scale', 0.0035, ...
        'crowding_sensitivity_threshold_m', 0.210, ...
        'early_robot_release_frames', 18);

    scenarios(5) = struct( ...
        'name', 'robot_overlap_pressure', ...
        'human_speed_range', [0.080, 0.095], ...
        'robot_speed_range', [0.100, 0.120], ...
        'hesitation_progress_range', [0.45, 0.65], ...
        'hesitation_duration_range', [22, 32], ...
        'escalation', true, ...
        'rework_progress_range', [0.00, 0.00], ...
        'jitter_scale', 0.004, ...
        'crowding_sensitivity_threshold_m', 0.235, ...
        'early_robot_release_frames', 4);
end
