function scenarios = buildABScenarioLibrary()
% buildABScenarioLibrary: Return initial scenario family definitions.

    scenarios = struct([]);

    scenarios(1) = struct( ...
        'name', 'nominal_handoff', ...
        'environment_name', 'low_conflict_open', ...
        'human_speed_range', [0.085, 0.100], ...
        'robot_speed_range', [0.080, 0.095], ...
        'hesitation_progress_range', [0.00, 0.00], ...
        'hesitation_duration_range', [0, 0], ...
        'escalation', false, ...
        'rework_progress_range', [0.00, 0.00], ...
        'jitter_scale', 0.002, ...
        'crowding_sensitivity_threshold_m', 0.22, ...
        'early_robot_release_frames', 18, ...
        'task_precision_required', 0.2, ...
        'workspace_constraint_level', 0.1, ...
        'expected_task_duration_sec', 20.0, ...
        'expected_pause_duration_sec', 1.0, ...
        'occlusion_level', 0.0, ...
        'ghost_proximity_level', 0.0);

    scenarios(2) = struct( ...
        'name', 'mild_pause_approach', ...
        'environment_name', 'narrow_assembly_bench', ...
        'human_speed_range', [0.080, 0.095], ...
        'robot_speed_range', [0.080, 0.095], ...
        'hesitation_progress_range', [0.35, 0.55], ...
        'hesitation_duration_range', [18, 28], ...
        'escalation', false, ...
        'rework_progress_range', [0.00, 0.00], ...
        'jitter_scale', 0.003, ...
        'crowding_sensitivity_threshold_m', 0.215, ...
        'early_robot_release_frames', 18, ...
        'task_precision_required', 0.3, ...
        'workspace_constraint_level', 0.9, ...
        'expected_task_duration_sec', 24.0, ...
        'expected_pause_duration_sec', 1.4, ...
        'occlusion_level', 0.0, ...
        'ghost_proximity_level', 0.0);

    scenarios(3) = struct( ...
        'name', 'strong_pause_near_zone', ...
        'environment_name', 'narrow_assembly_bench', ...
        'human_speed_range', [0.075, 0.090], ...
        'robot_speed_range', [0.085, 0.100], ...
        'hesitation_progress_range', [0.50, 0.70], ...
        'hesitation_duration_range', [28, 42], ...
        'escalation', true, ...
        'rework_progress_range', [0.00, 0.00], ...
        'jitter_scale', 0.0035, ...
        'crowding_sensitivity_threshold_m', 0.205, ...
        'early_robot_release_frames', 20, ...
        'task_precision_required', 0.4, ...
        'workspace_constraint_level', 0.9, ...
        'expected_task_duration_sec', 26.0, ...
        'expected_pause_duration_sec', 1.6, ...
        'occlusion_level', 0.0, ...
        'ghost_proximity_level', 0.0);

    scenarios(4) = struct( ...
        'name', 'correction_rework_midtask', ...
        'environment_name', 'inspection_rework', ...
        'human_speed_range', [0.078, 0.092], ...
        'robot_speed_range', [0.082, 0.098], ...
        'hesitation_progress_range', [0.20, 0.35], ...
        'hesitation_duration_range', [10, 20], ...
        'escalation', false, ...
        'rework_progress_range', [0.60, 0.75], ...
        'jitter_scale', 0.0035, ...
        'crowding_sensitivity_threshold_m', 0.210, ...
        'early_robot_release_frames', 18, ...
        'task_precision_required', 0.7, ...
        'workspace_constraint_level', 0.6, ...
        'expected_task_duration_sec', 30.0, ...
        'expected_pause_duration_sec', 3.0, ...
        'occlusion_level', 0.1, ...
        'ghost_proximity_level', 0.0);

    scenarios(5) = struct( ...
        'name', 'robot_overlap_pressure', ...
        'environment_name', 'precision_insertion', ...
        'human_speed_range', [0.080, 0.095], ...
        'robot_speed_range', [0.100, 0.120], ...
        'hesitation_progress_range', [0.45, 0.65], ...
        'hesitation_duration_range', [22, 32], ...
        'escalation', true, ...
        'rework_progress_range', [0.00, 0.00], ...
        'jitter_scale', 0.004, ...
        'crowding_sensitivity_threshold_m', 0.235, ...
        'early_robot_release_frames', 4, ...
        'task_precision_required', 1.0, ...
        'workspace_constraint_level', 0.5, ...
        'expected_task_duration_sec', 36.0, ...
        'expected_pause_duration_sec', 5.0, ...
        'occlusion_level', 0.0, ...
        'ghost_proximity_level', 0.0);

    scenarios(6) = struct( ...
        'name', 'sensor_occlusion', ...
        'environment_name', 'sensor_occlusion', ...
        'human_speed_range', [0.078, 0.096], ...
        'robot_speed_range', [0.084, 0.102], ...
        'hesitation_progress_range', [0.42, 0.64], ...
        'hesitation_duration_range', [18, 30], ...
        'escalation', true, ...
        'rework_progress_range', [0.30, 0.55], ...
        'jitter_scale', 0.0045, ...
        'crowding_sensitivity_threshold_m', 0.225, ...
        'early_robot_release_frames', 14, ...
        'task_precision_required', 0.45, ...
        'workspace_constraint_level', 0.65, ...
        'expected_task_duration_sec', 32.0, ...
        'expected_pause_duration_sec', 2.4, ...
        'occlusion_level', 0.85, ...
        'ghost_proximity_level', 0.0);

    scenarios(7) = struct( ...
        'name', 'ghost_proximity', ...
        'environment_name', 'ghost_proximity', ...
        'human_speed_range', [0.080, 0.098], ...
        'robot_speed_range', [0.090, 0.110], ...
        'hesitation_progress_range', [0.48, 0.72], ...
        'hesitation_duration_range', [16, 30], ...
        'escalation', true, ...
        'rework_progress_range', [0.25, 0.50], ...
        'jitter_scale', 0.0050, ...
        'crowding_sensitivity_threshold_m', 0.230, ...
        'early_robot_release_frames', 12, ...
        'task_precision_required', 0.35, ...
        'workspace_constraint_level', 0.72, ...
        'expected_task_duration_sec', 31.0, ...
        'expected_pause_duration_sec', 2.0, ...
        'occlusion_level', 0.35, ...
        'ghost_proximity_level', 0.90);
end
