function metrics = computeABEpisodeMetrics(frame_log, schedule, config)
% computeABEpisodeMetrics: Reduce one episode frame log into summary metrics.

    completion_time_sec = frame_log(end).time_sec + config.dt_sec;
    human_states = {frame_log.human_state};
    robot_modes = {frame_log.robot_mode};
    robot_speed_scale = [frame_log.robot_speed_scale];
    simultaneous_shared = [frame_log.simultaneous_shared_zone];
    overlap_events = countTransitions(simultaneous_shared);
    unsafe_events = countTransitions([frame_log.emergency_active]);

    metrics = struct( ...
        'scenario_name', schedule.scenario_name, ...
        'seed', schedule.seed, ...
        'policy_name', '', ...
        'backend', '', ...
        'success', double(strcmp(frame_log(end).human_state, 'done')), ...
        'completion_time_sec', completion_time_sec, ...
        'min_separation_m', min([frame_log.separation_m]), ...
        'overlap_event_count', overlap_events, ...
        'overlap_frames', sum(simultaneous_shared), ...
        'unsafe_close_call_count', unsafe_events, ...
        'robot_wait_time_sec', sum(strcmp(robot_modes, 'hold') | strcmp(robot_modes, 'emergency_stop')) * config.dt_sec, ...
        'human_wait_time_sec', sum([frame_log.human_speed] < 1e-6) * config.dt_sec, ...
        'robot_hold_count', countTransitions(strcmp(robot_modes, 'hold')), ...
        'robot_slow_frames', sum(strcmp(robot_modes, 'slow')), ...
        'policy_intervention_frames', sum(strcmp(robot_modes, 'hold') | strcmp(robot_modes, 'slow')), ...
        'human_rework_count', max([frame_log.retry_count]), ...
        'mild_hesitation_time_sec', sum(strcmp(human_states, 'mild_hesitation')) * config.dt_sec, ...
        'strong_hesitation_time_sec', sum(strcmp(human_states, 'strong_hesitation')) * config.dt_sec, ...
        'response_latency_sec', NaN, ...
        'mean_robot_speed_scale', mean(robot_speed_scale), ...
        'shared_zone_simultaneous_frames', sum(simultaneous_shared));
end

function count = countTransitions(flag_values)
    if isempty(flag_values)
        count = 0;
        return;
    end

    count = 0;
    previous = false;
    for idx = 1:numel(flag_values)
        current = logical(flag_values(idx));
        if current && ~previous
            count = count + 1;
        end
        previous = current;
    end
end
