function prediction = inferHesitationHeuristic(features, config)
% inferHesitationHeuristic: Deterministic inference stub with Python-CLI-compatible schema.

    state = 'normal_progress';
    if double(features.retry_count) > 0 && features.progress_delta < config.heuristic.rework_progress_delta_threshold
        state = 'correction_rework';
    elseif features.pause_ratio >= config.heuristic.pause_ratio_strong || features.mean_hand_speed < config.heuristic.mean_speed_strong
        state = 'strong_hesitation';
    elseif features.pause_ratio >= config.heuristic.pause_ratio_mild || ...
            features.mean_hand_speed < config.heuristic.mean_speed_mild || ...
            double(features.reversal_count) >= config.heuristic.reversal_mild_count || ...
            features.human_robot_distance < config.heuristic.distance_mild
        state = 'mild_hesitation';
    end

    probabilities = buildProbabilities(state);
    prediction = struct( ...
        'state', state, ...
        'state_probabilities', probabilities, ...
        'future_hesitation_prob', futureHesitationProbability(state), ...
        'future_correction_prob', futureCorrectionProbability(state), ...
        'confidence', probabilities.(state), ...
        'window_size_frames', config.window_size_frames, ...
        'frame_rate_hz', config.frame_rate_hz);
end

function probabilities = buildProbabilities(state)
    switch state
        case 'normal_progress'
            probabilities = struct( ...
                'normal_progress', 0.88, ...
                'mild_hesitation', 0.06, ...
                'strong_hesitation', 0.03, ...
                'correction_rework', 0.03, ...
                'ready_for_robot_action', 0.00, ...
                'overlap_risk', 0.00);
        case 'mild_hesitation'
            probabilities = struct( ...
                'normal_progress', 0.08, ...
                'mild_hesitation', 0.78, ...
                'strong_hesitation', 0.08, ...
                'correction_rework', 0.06, ...
                'ready_for_robot_action', 0.00, ...
                'overlap_risk', 0.00);
        case 'strong_hesitation'
            probabilities = struct( ...
                'normal_progress', 0.03, ...
                'mild_hesitation', 0.12, ...
                'strong_hesitation', 0.80, ...
                'correction_rework', 0.05, ...
                'ready_for_robot_action', 0.00, ...
                'overlap_risk', 0.00);
        case 'correction_rework'
            probabilities = struct( ...
                'normal_progress', 0.02, ...
                'mild_hesitation', 0.08, ...
                'strong_hesitation', 0.04, ...
                'correction_rework', 0.86, ...
                'ready_for_robot_action', 0.00, ...
                'overlap_risk', 0.00);
        otherwise
            probabilities = struct( ...
                'normal_progress', 0.88, ...
                'mild_hesitation', 0.06, ...
                'strong_hesitation', 0.03, ...
                'correction_rework', 0.03, ...
                'ready_for_robot_action', 0.00, ...
                'overlap_risk', 0.00);
    end
end

function value = futureHesitationProbability(state)
    switch state
        case 'normal_progress'
            value = 0.12;
        case 'mild_hesitation'
            value = 0.58;
        case 'strong_hesitation'
            value = 0.86;
        case 'correction_rework'
            value = 0.72;
        otherwise
            value = 0.20;
    end
end

function value = futureCorrectionProbability(state)
    switch state
        case 'correction_rework'
            value = 0.76;
        case 'strong_hesitation'
            value = 0.34;
        case 'mild_hesitation'
            value = 0.18;
        otherwise
            value = 0.08;
    end
end
