function [episode_summary, frame_log] = runABEpisode(policy_name, schedule, config)
% runABEpisode: Run one deterministic A/B episode and return frame log + summary.

    if strcmp(config.backend, 'python_bridge')
        cli_handle = HesitationModelCLI(config.python.model_root_dir);
        cli_handle.python_cmd = config.python.python_cmd;
    else
        cli_handle = [];
    end

    sim = initializeSimulation(policy_name, schedule, config);
    frame_log = repmat(initialFrameStruct(), config.max_frames, 1);
    prediction = defaultPrediction(config);
    hesitation_onset_time = NaN;
    first_intervention_time = NaN;

    for frame_idx = 1:config.max_frames
        sim.frame_idx = frame_idx;
        sim.time_sec = (frame_idx - 1) * config.dt_sec;

        sim = updateInteraction(sim, schedule, config);
        [sim.human, event_flags] = stepHumanStateMachine( ...
            sim.human, sim.robot, sim.interaction, schedule, config, frame_idx);
        sim = updateInteraction(sim, schedule, config);
        [features, sim.buffers] = extractRollingFeatures2D( ...
            sim.buffers, sim.human, sim.robot, sim.interaction, event_flags.task_restart, config);

        if frame_idx >= config.warmup_frames && mod(frame_idx, config.inference_stride_frames) == 0
            if strcmp(config.backend, 'python_bridge')
                [prediction, cli_handle] = inferHesitationPythonBridge(features, config, cli_handle);
            else
                prediction = inferHesitationHeuristic(features, config);
            end
            sim.inference.last_prediction = prediction;
            sim.inference.last_features = features;
            sim.inference.last_update_frame = frame_idx;
        else
            prediction = sim.inference.last_prediction;
            features = sim.inference.last_features;
        end

        if isnan(hesitation_onset_time) && ...
                (strcmp(sim.human.state, 'mild_hesitation') || strcmp(sim.human.state, 'strong_hesitation') || strcmp(sim.human.state, 'correction_rework'))
            hesitation_onset_time = sim.time_sec;
        end

        sim.robot = stepRobotPolicy(sim.robot, sim.human, sim.interaction, prediction, policy_name, schedule, config, frame_idx);
        sim = updateInteraction(sim, schedule, config);

        if strcmp(policy_name, 'B') && isnan(first_intervention_time) && ...
                (strcmp(sim.robot.mode, 'hold') || strcmp(sim.robot.mode, 'slow')) && ~isnan(hesitation_onset_time)
            first_intervention_time = sim.time_sec;
        end

        frame_log(frame_idx) = buildFrameRow(sim, schedule, features, prediction);

        if strcmp(sim.human.state, 'done') && sim.robot.completed
            frame_log = frame_log(1:frame_idx);
            break;
        end
    end

    if numel(frame_log) > config.max_frames
        frame_log = frame_log(1:config.max_frames);
    end

    episode_summary = computeABEpisodeMetrics(frame_log, schedule, config);
    episode_summary.policy_name = policy_name;
    episode_summary.backend = config.backend;
    episode_summary.response_latency_sec = NaN;
    if ~isnan(hesitation_onset_time) && ~isnan(first_intervention_time)
        episode_summary.response_latency_sec = max(first_intervention_time - hesitation_onset_time, 0.0);
    end
end

function sim = initializeSimulation(policy_name, schedule, config)
    sim = struct( ...
        'dt_sec', config.dt_sec, ...
        'frame_rate_hz', config.frame_rate_hz, ...
        'max_frames', config.max_frames, ...
        'frame_idx', 0, ...
        'time_sec', 0.0, ...
        'seed', schedule.seed, ...
        'scenario_name', schedule.scenario_name, ...
        'policy_name', policy_name, ...
        'backend', config.backend, ...
        'workspace', config.workspace, ...
        'human', initializeHuman(config), ...
        'robot', initializeRobot(schedule, config), ...
        'interaction', initializeInteraction(), ...
        'buffers', initializeBuffers(), ...
        'inference', initializeInference(config));
end

function human = initializeHuman(config)
    human = struct( ...
        'state', 'normal_progress', ...
        'pos_xy', config.workspace.human_start_xy, ...
        'vel_xy', [0.0, 0.0], ...
        'target_idx', 2, ...
        'progress_01', 0.0, ...
        'last_progress_01', 0.0, ...
        'progress_trend_positive', true, ...
        'state_age_frames', 0, ...
        'wait_frames', 0, ...
        'rework_count', 0, ...
        'rework_triggered', false, ...
        'resume_target_idx', 2, ...
        'mild_frames', 0, ...
        'strong_frames', 0, ...
        'crowding_frames_mild', 0, ...
        'crowding_frames_strong', 0, ...
        'stable_release_frames', 0);
end

function robot = initializeRobot(schedule, config)
    robot = struct( ...
        'mode', 'proceed', ...
        'pos_xy', config.workspace.robot_start_xy, ...
        'vel_xy', [0.0, 0.0], ...
        'target_idx', 2, ...
        'speed_scale_cmd', 1.0, ...
        'hold_count', 0, ...
        'wait_frames', 0, ...
        'slow_frames', 0, ...
        'release_stable_frames', 0, ...
        'completed', false, ...
        'state_changed', false);
end

function interaction = initializeInteraction()
    interaction = struct( ...
        'separation_m', inf, ...
        'human_in_shared_zone', false, ...
        'robot_in_shared_zone', false, ...
        'simultaneous_shared_zone', false, ...
        'overlap_event_count', 0, ...
        'unsafe_close_call_count', 0, ...
        'min_separation_m', inf, ...
        'previous_simultaneous_shared_zone', false, ...
        'previous_unsafe_close', false);
end

function buffers = initializeBuffers()
    buffers = struct( ...
        'human_pos_xy', [], ...
        'human_speed', [], ...
        'progress', [], ...
        'separation', [], ...
        'task_restart_flag', []);
end

function inference = initializeInference(config)
    inference = struct( ...
        'last_prediction', defaultPrediction(config), ...
        'last_features', defaultFeatures(), ...
        'last_update_frame', 0);
end

function prediction = defaultPrediction(config)
    prediction = struct( ...
        'state', 'normal_progress', ...
        'state_probabilities', struct( ...
            'normal_progress', 1.0, ...
            'mild_hesitation', 0.0, ...
            'strong_hesitation', 0.0, ...
            'correction_rework', 0.0, ...
            'ready_for_robot_action', 0.0, ...
            'overlap_risk', 0.0), ...
        'future_hesitation_prob', 0.0, ...
        'future_correction_prob', 0.0, ...
        'confidence', 1.0, ...
        'window_size_frames', config.window_size_frames, ...
        'frame_rate_hz', config.frame_rate_hz);
end

function features = defaultFeatures()
    features = struct( ...
        'mean_hand_speed', 0.0, ...
        'pause_ratio', 0.0, ...
        'progress_delta', 0.0, ...
        'reversal_count', int32(0), ...
        'retry_count', int32(0), ...
        'task_step_id', int32(0), ...
        'human_robot_distance', 1.0);
end

function sim = updateInteraction(sim, schedule, config)
    separation = norm(sim.human.pos_xy - sim.robot.pos_xy);
    human_in_shared = norm(sim.human.pos_xy - config.workspace.shared_zone_center_xy) <= config.workspace.shared_zone_radius_m;
    robot_in_shared = norm(sim.robot.pos_xy - config.workspace.shared_zone_center_xy) <= config.workspace.shared_zone_radius_m;
    simultaneous = human_in_shared && robot_in_shared;
    unsafe_close = separation < config.workspace.hard_safety_radius_m;

    sim.interaction.separation_m = separation;
    sim.interaction.human_in_shared_zone = human_in_shared;
    sim.interaction.robot_in_shared_zone = robot_in_shared;
    sim.interaction.simultaneous_shared_zone = simultaneous;
    sim.interaction.min_separation_m = min(sim.interaction.min_separation_m, separation);

    if simultaneous && ~sim.interaction.previous_simultaneous_shared_zone
        sim.interaction.overlap_event_count = sim.interaction.overlap_event_count + 1;
    end
    if unsafe_close && ~sim.interaction.previous_unsafe_close
        sim.interaction.unsafe_close_call_count = sim.interaction.unsafe_close_call_count + 1;
    end

    sim.interaction.previous_simultaneous_shared_zone = simultaneous;
    sim.interaction.previous_unsafe_close = unsafe_close;

    threshold = min(schedule.crowding_sensitivity_threshold_m, config.human.crowding_mild_threshold_m);
    if separation < threshold
        sim.human.crowding_frames_mild = sim.human.crowding_frames_mild + 1;
    else
        sim.human.crowding_frames_mild = 0;
    end

    if separation < config.human.crowding_strong_threshold_m
        sim.human.crowding_frames_strong = sim.human.crowding_frames_strong + 1;
    else
        sim.human.crowding_frames_strong = 0;
    end

    if separation > 0.25 && ~robot_in_shared
        sim.human.stable_release_frames = sim.human.stable_release_frames + 1;
    else
        sim.human.stable_release_frames = 0;
    end
end

function row = buildFrameRow(sim, schedule, features, prediction)
    row = initialFrameStruct();
    row.scenario_name = sim.scenario_name;
    row.seed = schedule.seed;
    row.policy_name = sim.policy_name;
    row.backend = sim.backend;
    row.frame_idx = sim.frame_idx;
    row.time_sec = sim.time_sec;
    row.human_state = sim.human.state;
    row.human_pos_x = sim.human.pos_xy(1);
    row.human_pos_y = sim.human.pos_xy(2);
    row.robot_pos_x = sim.robot.pos_xy(1);
    row.robot_pos_y = sim.robot.pos_xy(2);
    row.separation_m = sim.interaction.separation_m;
    row.human_in_shared_zone = double(sim.interaction.human_in_shared_zone);
    row.robot_in_shared_zone = double(sim.interaction.robot_in_shared_zone);
    row.simultaneous_shared_zone = double(sim.interaction.simultaneous_shared_zone);
    row.mean_hand_speed = features.mean_hand_speed;
    row.pause_ratio = features.pause_ratio;
    row.progress_delta = features.progress_delta;
    row.reversal_count = double(features.reversal_count);
    row.retry_count = double(features.retry_count);
    row.task_step_id = double(features.task_step_id);
    row.human_robot_distance = features.human_robot_distance;
    row.predicted_state = prediction.state;
    row.future_hesitation_prob = prediction.future_hesitation_prob;
    row.future_correction_prob = prediction.future_correction_prob;
    row.prediction_confidence = prediction.confidence;
    row.robot_mode = sim.robot.mode;
    row.robot_speed_scale = sim.robot.speed_scale_cmd;
    row.policy_intervention_active = double(strcmp(sim.robot.mode, 'hold') || strcmp(sim.robot.mode, 'slow'));
    row.emergency_active = double(strcmp(sim.robot.mode, 'emergency_stop'));
    row.human_speed = norm(sim.human.vel_xy);
    row.human_progress_01 = sim.human.progress_01;
end

function row = initialFrameStruct()
    row = struct( ...
        'scenario_name', '', ...
        'seed', 0, ...
        'policy_name', '', ...
        'backend', '', ...
        'frame_idx', 0, ...
        'time_sec', 0.0, ...
        'human_state', '', ...
        'human_pos_x', 0.0, ...
        'human_pos_y', 0.0, ...
        'robot_pos_x', 0.0, ...
        'robot_pos_y', 0.0, ...
        'separation_m', 0.0, ...
        'human_in_shared_zone', 0, ...
        'robot_in_shared_zone', 0, ...
        'simultaneous_shared_zone', 0, ...
        'mean_hand_speed', 0.0, ...
        'pause_ratio', 0.0, ...
        'progress_delta', 0.0, ...
        'reversal_count', 0, ...
        'retry_count', 0, ...
        'task_step_id', 0, ...
        'human_robot_distance', 0.0, ...
        'predicted_state', '', ...
        'future_hesitation_prob', 0.0, ...
        'future_correction_prob', 0.0, ...
        'prediction_confidence', 0.0, ...
        'robot_mode', '', ...
        'robot_speed_scale', 0.0, ...
        'policy_intervention_active', 0, ...
        'emergency_active', 0, ...
        'human_speed', 0.0, ...
        'human_progress_01', 0.0);
end

function pos_xy = clampToBounds(pos_xy, bounds_xy)
    pos_xy(1) = min(max(pos_xy(1), bounds_xy(1, 1)), bounds_xy(1, 2));
    pos_xy(2) = min(max(pos_xy(2), bounds_xy(2, 1)), bounds_xy(2, 2));
end
